"""pvdata table

Revision ID: f5dd7b89d44b
Revises: 
Create Date: 2019-10-04 18:21:48.237942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5dd7b89d44b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pv_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('grid_voltage', sa.Float(), nullable=False),
    sa.Column('grid_current', sa.Float(), nullable=False),
    sa.Column('grid_power', sa.Integer(), nullable=False),
    sa.Column('invert_temp', sa.Float(), nullable=False),
    sa.Column('booster_temp', sa.Float(), nullable=False),
    sa.Column('pwr_peak', sa.Integer(), nullable=False),
    sa.Column('pwr_peak_td', sa.Integer(), nullable=False),
    sa.Column('nrg', sa.Integer(), nullable=False),
    sa.Column('nrg_td', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pv_data')
    # ### end Alembic commands ###
